-- ============================================================================
-- dian-scraper-test — bootstrap schema
-- ----------------------------------------------------------------------------
-- Runs ONCE on a fresh postgres container (mounted into
-- /docker-entrypoint-initdb.d/01-bootstrap.sql). After the first deploy,
-- schema changes should be additive and idempotent — never rerun a
-- destructive ALTER from this file.
--
-- We use IF NOT EXISTS throughout so re-running the script against an
-- existing DB is a no-op. New tables/columns should be added the same
-- way (additive only) or via a separate migration step.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- jobs: one row per scraping job the API accepts
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS jobs (
  -- UUIDv4 generated by the API at POST time. Matches the value NUVARA
  -- already persists in dian_scraper_alt_runs.job_id, so the two sides
  -- can correlate without a join table.
  id                  TEXT PRIMARY KEY,

  -- Tenant id passed from NUVARA. We never use it to authorize anything
  -- here; the scraper is single-tenant from a security perspective. We
  -- keep it so audit logs + R2 prefixes (`dian-scraper-alt/{company}/...`)
  -- are scoped correctly. CHECK rejects malformed UUIDs early so a typo
  -- in NUVARA can't poison the bucket layout.
  company_id          TEXT
                      CHECK (
                        company_id IS NULL
                        OR company_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
                      ),

  -- Lifecycle. The API never deletes a row; it transitions status.
  --   queued     → just accepted, no worker took it yet
  --   running    → claimed by a worker, scraping in progress
  --   completed  → engine finished successfully
  --   failed     → engine raised an exception (see `error`)
  --   cancelled  → operator pressed cancel
  status              TEXT NOT NULL CHECK (status IN
                        ('queued','running','completed','failed','cancelled')),

  -- Request payload, kept verbatim so an operator can reproduce a
  -- bad run with the same input.
  auth_url            TEXT NOT NULL,
  start_date          DATE NOT NULL,
  end_date            DATE NOT NULL,
  max_invoices        INT  NOT NULL,

  -- Worker identity + heartbeat for crash recovery. A reaper sweeps
  -- jobs whose heartbeat is older than 3 min and flips them to failed
  -- so NUVARA can decide whether to retry.
  worker_id           TEXT,
  worker_heartbeat    TIMESTAMPTZ,

  -- Wall-clock timestamps.
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at          TIMESTAMPTZ,
  finished_at         TIMESTAMPTZ,

  -- Engine summary at the end of a successful run.
  --   { "total": N, "ok": M, "failed": K }
  summary             JSONB,

  -- Free-form error text when status='failed'.
  error               TEXT,

  -- Classified error kind, stable vocabulary the consumer (NUVARA)
  -- maps to a context-aware UI message:
  --   auth_expired         single-use token had already been consumed
  --   auth_expired_midrun  session lapsed after some downloads
  --   captcha_blocked      WAF held the browser out of the portal
  --   timeout              hit the global job budget
  --   engine_crash         unhandled exception in the Playwright loop
  -- NULL for completed/cancelled runs and legacy rows.
  error_kind          TEXT
);

-- Idempotent ALTER for databases that were bootstrapped before
-- error_kind existed. Safe to re-run on every container start.
ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS error_kind TEXT;

CREATE INDEX IF NOT EXISTS jobs_status_heartbeat_idx
  ON jobs (status, worker_heartbeat)
  WHERE status = 'running';

CREATE INDEX IF NOT EXISTS jobs_company_created_idx
  ON jobs (company_id, created_at DESC);


-- ────────────────────────────────────────────────────────────────────────────
-- job_files: one row per ZIP the engine successfully downloaded
-- ────────────────────────────────────────────────────────────────────────────
-- The scraper persists files in two modes:
--   STORAGE_MODE=local → r2_key is null, files served from /files/...
--   STORAGE_MODE=r2    → r2_key is set, NUVARA reads R2 directly.
-- One row per ZIP regardless of mode so the audit trail is uniform.
CREATE TABLE IF NOT EXISTS job_files (
  id                  BIGSERIAL PRIMARY KEY,
  job_id              TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,

  -- CUFE may be null when the engine could not extract it from the
  -- portal listing. We keep the row anyway so the operator sees the
  -- orphan file in NUVARA.
  cufe                TEXT,
  prefijo_folio       TEXT,
  issuer_nit          TEXT,
  issue_date          DATE,

  -- One of 'zip' | 'pdf' | 'xml' | 'bin'. The engine collapses ZIPs
  -- internally so by the time we hit this table the file is the raw
  -- DIAN ZIP — the kind column is forward-looking.
  kind                TEXT NOT NULL,

  -- Filename as the engine wrote it (e.g. `{cufe[:20]}.zip`).
  name                TEXT NOT NULL,
  size_bytes          BIGINT NOT NULL,

  -- Populated only when STORAGE_MODE=r2.
  r2_key              TEXT,
  r2_url              TEXT,

  uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS job_files_job_id_idx ON job_files (job_id);


-- ────────────────────────────────────────────────────────────────────────────
-- job_events: append-only event log for the live console
-- ────────────────────────────────────────────────────────────────────────────
-- Mirrors what the legacy in-memory RunState.events used to hold.
-- NUVARA polls GET /api/jobs/{id}/events?since=N → reads from here.
CREATE TABLE IF NOT EXISTS job_events (
  -- Composite PK: monotonic per job. NUVARA passes the highest seen
  -- value as `since` on the next poll so the server doesn't resend
  -- the whole log.
  job_id              TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  event_index         BIGINT NOT NULL,

  -- 'worker' → emitted by the python loop (lifecycle, retries, …)
  -- 'engine' → emitted by Playwright inside the scraper (per-CUFE)
  source              TEXT NOT NULL,

  -- Free-form taxonomy. Matches what NUVARA's UI already renders.
  phase               TEXT NOT NULL,
  status              TEXT NOT NULL,

  message             TEXT,
  payload             JSONB,

  -- Engine wall clock — may drift from server clock if the worker
  -- runs in a different TZ container. NUVARA always trusts this one.
  occurred_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (job_id, event_index)
);

CREATE INDEX IF NOT EXISTS job_events_job_occurred_idx
  ON job_events (job_id, occurred_at);
